[server]
headless = true
port = 8501
maxUploadSize = 500
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"

[global]
# Configuración UTF-8
dataFrameSerialization = "legacy"

[browser]
gatherUsageStats = false

[theme]
# Fuerza tema oscuro permanente (ignora configuración del navegador)
base = "dark"
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[ui]
# Ocultar elementos de la interfaz de Streamlit
hideTopBar = true
