[server]
headless = true
port = 8501
maxUploadSize = 500
enableCORS = false
enableXsrfProtection = true

[global]
developmentMode = false
dataFrameSerialization = "legacy"

[theme]
base = "light"
primaryColor = "#FF4B4B"
